### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by paladin-t** [nibbleteam/nibble#57]
Hi,

Nibble doesn't work properly on my system:

![image](https://user-images.githubusercontent.com/2062224/75092146-f8cc5580-55af-11ea-9d09-07435554ab0d.png)

and the console outputs:

![image](https://user-images.githubusercontent.com/2062224/75092151-05e94480-55b0-11ea-97e3-769df49fe9f9.png)

I'm running it on Win10 64bit, language and region set Chinese. And as you can see in the screenshot, the start path doesn't contain any non-ascii character or space. I also tried to run it under compatibility modes, but sadly it's all the same.

Thanks for your time.

**Comment by felipetavares** [comment]
Hey @paladin-t, thanks for reporting this.

Can you provide more info about your hardware? Specifically, knowing what GPU you are using and the driver versions would be perfect.

**Comment by paladin-t** [comment]
Thanks for your reply.

FYI. it works perfect on my Win7 desktop. Don't have a chance to test it on other Win10 yet.

It is produced on my ThinkPad x230t laptop:

* Intel Core i5-3320m CPU@2.60GHz
* 16GB RAM
* Intel HD Graphics 4000 GPU
* Win10 ver 1909 (18363.657)

and the GPU driver is:

![image](https://user-images.githubusercontent.com/2062224/75111942-08b06c00-567a-11ea-8a94-4fe829de8463.png)

**Comment by felipetavares** [comment]
It seems to be a driver issue.

Unfortunately, many drivers do not provide logs when linking shaders, which is what is happening here. We see that there was an error but no other information is provided.

I found a stackoverflow question which seems to be a similar issue (on an HD 3000), maybe you can check it:

https://stackoverflow.com/questions/8599607/opengl-gllinkprogram-returns-false-but-info-log-is-empty-checked-everything

**Comment by felipetavares** [comment]
I improved a bit the shader linking logging.

If you want you can try that in the latest build, it should have a bit of extra information in the console:

https://github.com/nibbleteam/nibble/actions/runs/100364343
