### ISSUE TITLE
No Windows x86 builds

### ISSUE THREAD

**Issue by felipetavares** [nibbleteam/nibble#58]
There is a part of the userbase with no access to x64 CPUs, for them a x86 build is necessary.

**Comment by The-Beesh-Spweesh** [comment]
Why did you kick me from the Discord? Also like I said, I'm only _partially_ an x86 user.

**Comment by felipetavares** [comment]
@StinkerB06 how are you entering the community? It seems our server is kicking unregistered users or something to that effect, I'm checking our settings.

**Comment by The-Beesh-Spweesh** [comment]
I found the Discord link directly from the website.

**Comment by felipetavares** [comment]
It seems our link was granting only temporary membership until you leave, I'll be fixing that shortly.

**Comment by felipetavares** [comment]
@StinkerB06 turns out we are already building for x86. The problematic one I mentioned is the x64 build.

I messed up with the naming: the `.x64.` one is actually a x86 build.

Can you test if it works for you?

**Comment by felipetavares** [comment]
Renamed in the release. Now it shows correctly as x86.
